
// Generated by the mtime code generator.  DO NOT EDIT!
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

package cmc.admin.stc.web.enums;

import lucky.sky.util.lang.EnumDisplayNameSupport;
import lucky.sky.util.lang.EnumValueSupport;
import lucky.sky.util.lang.Enums;

/**
 * 电影状态
**/
public enum MovieStatus implements EnumValueSupport, EnumDisplayNameSupport {

	/**
	 * 新建
	**/
	NEW(1, "新建"),
	/**
	 * 发布
	**/
	PUBLISH(2, "发布"),
	/**
	 * 下线
	**/
	OFFLINE(3, "下线");

	private int value;
	private String displayName;

	private MovieStatus(int value, String displayName) {
		this.value = value;
		this.displayName = displayName;
	}

	public int value() {
		return this.value;
	}

	public String displayName() {
		return this.displayName;
	}

	public static MovieStatus valueOf(int value){
		return Enums.valueOf(MovieStatus.class, value);
	}
}
