
// Generated by the mtime code generator.  DO NOT EDIT!
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

package cmc.admin.stc.web.enums;

import lucky.sky.util.lang.EnumDisplayNameSupport;
import lucky.sky.util.lang.EnumValueSupport;
import lucky.sky.util.lang.Enums;

/**
 * 模板类型
**/
public enum PromoTemplateType implements EnumValueSupport, EnumDisplayNameSupport {

	/**
	 * 优惠券模板
	**/
	COUPON(1, "优惠券模板"),
	/**
	 * 促销模板
	**/
	STRATEGY(2, "促销模板"),
	/**
	 * 会员卡权益
	**/
	MCARD(3, "会员卡权益");

	private int value;
	private String displayName;

	private PromoTemplateType(int value, String displayName) {
		this.value = value;
		this.displayName = displayName;
	}

	public int value() {
		return this.value;
	}

	public String displayName() {
		return this.displayName;
	}

	public static PromoTemplateType valueOf(int value){
		return Enums.valueOf(PromoTemplateType.class, value);
	}
}
